# Generated by Django 4.2.6 on 2023-11-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailleDisponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AlterField(
            model_name='product',
            name='taille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.taille'),
        ),
    ]
