# Generated by Django 4.2.6 on 2023-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_taille_product_taille'),
    ]

    operations = [
        migrations.AddField(
            model_name='taille',
            name='taille',
            field=models.CharField(default='', max_length=32),
        ),
    ]
