# Generated by Django 4.2.6 on 2023-11-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_taille_taille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='taille',
        ),
        migrations.DeleteModel(
            name='Taille',
        ),
    ]
