# Generated by Django 4.2.6 on 2023-11-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_taille_product_taille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='taille',
            name='tailleDisponible',
        ),
        migrations.CreateModel(
            name='TailleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailleDisponible', models.BooleanField(default='true')),
                ('product', models.ManyToManyField(to='store.product')),
                ('taille', models.ManyToManyField(to='store.taille')),
            ],
        ),
    ]
