# Generated by Django 4.2.6 on 2023-11-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_product_taille_remove_taille_tailledisponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailleproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tailleproduct',
            name='taille',
        ),
        migrations.DeleteModel(
            name='Taille',
        ),
        migrations.DeleteModel(
            name='TailleProduct',
        ),
    ]
