# Generated by Django 4.2.6 on 2023-11-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_tailleproduct_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TailleDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailleDisponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TailleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='store.product')),
                ('taille', models.ManyToManyField(to='store.taille')),
                ('tailleDisponible', models.ManyToManyField(to='store.tailledisponible')),
            ],
        ),
    ]
