# Generated by Django 4.2.6 on 2023-11-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_taille_tailledisponible_tailleproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailleproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tailleproduct',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='tailleproduct',
            name='tailleDisponible',
        ),
        migrations.DeleteModel(
            name='Taille',
        ),
        migrations.DeleteModel(
            name='TailleDisponible',
        ),
        migrations.DeleteModel(
            name='TailleProduct',
        ),
    ]
