# Generated by Django 4.2.6 on 2023-11-08 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0025_remove_tailleproduct_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('prix', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
                ('taille', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.taille')),
            ],
        ),
        migrations.CreateModel(
            name='Jogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('prix', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
                ('taille', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.taille')),
            ],
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('prix', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
                ('taille', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.taille')),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('prix', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
                ('taille', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.taille')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cart',
            new_name='Commande',
        ),
        migrations.RemoveField(
            model_name='tailleproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tailleproduct',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='tailleproduct',
            name='tailleDisponible',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='TailleDisponible',
        ),
        migrations.DeleteModel(
            name='TailleProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='casquette',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.casquette'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='jogging',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.jogging'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pull',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.pull'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tshirt',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.tshirt'),
            preserve_default=False,
        ),
    ]
