# Generated by Django 4.2.6 on 2023-11-25 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0026_casquette_jogging_pull_tshirt_rename_cart_commande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('prix_unitaire', models.FloatField(default=0)),
                ('produit_defaut', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorie')),
            ],
        ),
        migrations.RemoveField(
            model_name='jogging',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='casquette',
        ),
        migrations.RemoveField(
            model_name='product',
            name='jogging',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pull',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tshirt',
        ),
        migrations.RemoveField(
            model_name='pull',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='orders',
        ),
        migrations.AddField(
            model_name='commande',
            name='information_paiement',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Casquette',
        ),
        migrations.DeleteModel(
            name='Jogging',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Pull',
        ),
        migrations.DeleteModel(
            name='Tshirt',
        ),
        migrations.AddField(
            model_name='couleur',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produit'),
        ),
        migrations.AddField(
            model_name='article',
            name='couleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.couleur'),
        ),
        migrations.AddField(
            model_name='article',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produit'),
        ),
        migrations.AddField(
            model_name='article',
            name='taille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.taille'),
        ),
        migrations.AddField(
            model_name='commande',
            name='articles',
            field=models.ManyToManyField(to='store.article'),
        ),
    ]
